export const permissions = [
  ['dashboard.read', 'Dashboard', 'View workspace overview'],
  ['users.read', 'Users', 'View company users'],
  ['roles.read', 'Roles', 'View roles and permissions'],
  ['sites.read', 'Plants', 'View assigned plants'],
  ['users.create', 'Users', 'Create company users'],
  ['users.update', 'Users', 'Edit company users'],
  ['users.change_status', 'Users', 'Activate or deactivate users'],
  ['users.assign_role', 'Users', 'Change a user role'],
  ['users.invite', 'Users', 'Send invitations'],
  ['users.reset_password', 'Users', 'Send password resets'],
  ['users.retry_setup', 'Users', 'Retry account setup'],
  ['users.assign_plants', 'Users', 'Assign user plant access'],
  ['roles.create', 'Roles', 'Create custom roles'],
  ['roles.update', 'Roles', 'Edit custom roles'],
  ['roles.delete', 'Roles', 'Delete unassigned custom roles'],
  ['sites.create', 'Plants', 'Create plants'],
  ['sites.update', 'Plants', 'Edit plants'],
  ['sites.change_status', 'Plants', 'Activate or deactivate plants'],
  ['sites.read_all', 'Plants', 'Access all company plants'],
  ['audit.read', 'Audit log', 'Read company audit history'],
  ['masters.read', 'Masters', 'View planning master data'],
  ['masters.manage', 'Masters', 'Maintain planning masters'],
  ['suppliers.manage', 'Masters', 'Maintain suppliers and item sourcing'],
  ['customers.manage', 'Masters', 'Maintain customers'],
  ['imports.create', 'Masters', 'Validate and import files'],
  ['orders.read', 'Demand', 'View customer and production orders'],
  ['orders.create', 'Demand', 'Create customer orders and import production orders'],
  ['orders.update', 'Demand', 'Edit and cancel customer orders'],
  ['demand.import', 'Demand', 'Import demand history'],
  ['inventory.read', 'Materials', 'View stock and movements'],
  ['inventory.move', 'Materials', 'Post stock receipts and issues'],
  ['inventory.adjust', 'Materials', 'Post opening stock, adjustments and reversals'],
  ['planning.read', 'Availability', 'View buffer board and planning results'],
  ['planning.run', 'Availability', 'Recalculate buffers on demand'],
  ['buffers.manage', 'Availability', 'Maintain buffer profiles and buffer settings'],
  ['schedule.publish', 'Availability', 'Publish a calculated schedule as the committed plan'],
  ['schedule.plan', 'Availability', 'Change the schedule: move, club and declub orders'],
  ['schedule.insert', 'Availability', 'Insert customer orders into the schedule and quote dates'],
  [
    'purchase.expedite',
    'Availability',
    'Approve expedite requests and record supplier confirmations',
  ],
  ['purchase.read', 'Materials', 'View purchase orders and proposals'],
  ['purchase.create', 'Materials', 'Create, edit and import purchase orders'],
  ['purchase.approve', 'Materials', 'Approve or reject purchase proposals'],
  ['work_orders.update', 'Production', 'Record production progress'],
  ['downtime.create', 'Production', 'Record resource downtime'],
  ['reports.export', 'Reporting', 'Export authorised records'],
];

export const requiredPermissions = {
  'users.create': ['users.read', 'roles.read'],
  'users.update': ['users.read', 'roles.read'],
  'users.change_status': ['users.read', 'users.update'],
  'users.assign_role': ['users.read', 'users.update'],
  'users.invite': ['users.read'],
  'users.reset_password': ['users.read'],
  'users.retry_setup': ['users.read'],
  'users.assign_plants': ['users.read', 'sites.read', 'sites.read_all', 'roles.read'],
  'roles.create': ['roles.read'],
  'roles.update': ['roles.read'],
  'roles.delete': ['roles.read'],
  'sites.create': ['sites.read'],
  'sites.update': ['sites.read'],
  'sites.change_status': ['sites.read', 'sites.update'],
  'sites.read_all': ['sites.read'],
  'masters.manage': ['masters.read'],
  'suppliers.manage': ['masters.read'],
  'customers.manage': ['masters.read'],
  'orders.create': ['orders.read', 'masters.read'],
  'orders.update': ['orders.read', 'masters.read'],
  'demand.import': ['orders.read', 'masters.read'],
  'inventory.read': ['masters.read'],
  'inventory.move': ['inventory.read'],
  'inventory.adjust': ['inventory.read'],
  'purchase.read': ['masters.read'],
  'purchase.create': ['purchase.read'],
  'purchase.approve': ['purchase.read'],
  'orders.read': ['masters.read'],
  'planning.read': ['masters.read'],
  'schedule.publish': ['planning.read'],
  'schedule.plan': ['planning.read'],
  'schedule.insert': ['planning.read'],
  'purchase.expedite': ['purchase.read', 'planning.read'],
  'planning.run': ['planning.read'],
  'buffers.manage': ['planning.read'],
  // Each import type also requires its own maintain permission, checked by the API.
  'imports.create': ['masters.read'],
};
export const livePermissionCodes = [
  'dashboard.read',
  'users.read',
  'roles.read',
  'sites.read',
  'audit.read',
  'users.create',
  'users.update',
  'users.change_status',
  'users.assign_role',
  'users.invite',
  'users.reset_password',
  'users.retry_setup',
  'users.assign_plants',
  'roles.create',
  'roles.update',
  'roles.delete',
  'sites.create',
  'sites.update',
  'sites.change_status',
  'sites.read_all',
  'masters.read',
  'masters.manage',
  'suppliers.manage',
  'customers.manage',
  'imports.create',
  'orders.read',
  'orders.create',
  'orders.update',
  'demand.import',
  'inventory.read',
  'inventory.move',
  'inventory.adjust',
  'purchase.read',
  'purchase.create',
  'purchase.approve',
  'planning.read',
  'planning.run',
  'buffers.manage',
  'schedule.publish',
  'schedule.plan',
  'schedule.insert',
  'purchase.expedite',
];
