export const permissions = [
  ['dashboard.read', 'Dashboard', 'View workspace overview'],
  ['users.read', 'Users', 'View company users'],
  ['roles.read', 'Roles', 'View roles and permissions'],
  ['sites.read', 'Plants', 'View assigned plants'],
  ['users.create', 'Users', 'Create company users'],
  ['users.update', 'Users', 'Edit company users'],
  ['users.change_status', 'Users', 'Activate or deactivate users'],
  ['users.assign_role', 'Users', 'Change a user role'],
  ['users.invite', 'Users', 'Send invitations'],
  ['users.reset_password', 'Users', 'Send password resets'],
  ['users.retry_setup', 'Users', 'Retry account setup'],
  ['users.assign_plants', 'Users', 'Assign user plant access'],
  ['roles.create', 'Roles', 'Create custom roles'],
  ['roles.update', 'Roles', 'Edit custom roles'],
  ['roles.delete', 'Roles', 'Delete unassigned custom roles'],
  ['sites.create', 'Plants', 'Create plants'],
  ['sites.update', 'Plants', 'Edit plants'],
  ['sites.change_status', 'Plants', 'Activate or deactivate plants'],
  ['sites.read_all', 'Plants', 'Access all company plants'],
  ['audit.read', 'Audit log', 'Read company audit history'],
  ['masters.read', 'Masters', 'View planning master data'],
  ['masters.manage', 'Masters', 'Maintain planning masters'],
  ['suppliers.manage', 'Masters', 'Maintain suppliers and item sourcing'],
  ['customers.manage', 'Masters', 'Maintain customers'],
  ['imports.create', 'Masters', 'Validate and import files'],
  ['orders.read', 'Demand', 'View customer and production orders'],
  ['orders.create', 'Demand', 'Create customer orders and import production orders'],
  ['orders.update', 'Demand', 'Edit and cancel customer orders'],
  ['demand.import', 'Demand', 'Import demand history'],
  ['inventory.read', 'Materials', 'View stock and movements'],
  ['inventory.move', 'Materials', 'Post stock receipts and issues'],
  ['inventory.adjust', 'Materials', 'Post opening stock, adjustments and reversals'],
  ['planning.read', 'Availability', 'View buffer board and planning results'],
  ['planning.run', 'Availability', 'Recalculate buffers on demand'],
  ['buffers.manage', 'Availability', 'Maintain buffer profiles and buffer settings'],
  ['schedule.publish', 'Availability', 'Publish a calculated schedule as the committed plan'],
  ['schedule.plan', 'Availability', 'Change the schedule: move, club and declub orders'],
  ['schedule.insert', 'Availability', 'Insert customer orders into the schedule and quote dates'],
  [
    'production.execute',
    'Availability',
    'Release make orders, release and complete work orders, log downtime',
  ],
  ['masters.cycle_time', 'Availability', 'Adopt corrected cycle times from completed work orders'],
  ['planning.tools', 'Availability', 'Maintain events, schemes, targets and space limits'],
  [
    'purchase.expedite',
    'Availability',
    'Approve expedite requests and record supplier confirmations',
  ],
  ['purchase.read', 'Materials', 'View purchase orders and proposals'],
  ['purchase.create', 'Materials', 'Create, edit and import purchase orders'],
  ['purchase.approve', 'Materials', 'Approve or reject purchase proposals'],
  ['work_orders.update', 'Production', 'Record production progress'],
  ['downtime.create', 'Production', 'Record resource downtime'],
  ['reports.export', 'Reporting', 'Export authorised records'],
];

export const requiredPermissions = {
  'users.create': ['users.read', 'roles.read'],
  'users.update': ['users.read', 'roles.read'],
  'users.change_status': ['users.read', 'users.update'],
  'users.assign_role': ['users.read', 'users.update'],
  'users.invite': ['users.read'],
  'users.reset_password': ['users.read'],
  'users.retry_setup': ['users.read'],
  'users.assign_plants': ['users.read', 'sites.read', 'sites.read_all', 'roles.read'],
  'roles.create': ['roles.read'],
  'roles.update': ['roles.read'],
  'roles.delete': ['roles.read'],
  'sites.create': ['sites.read'],
  'sites.update': ['sites.read'],
  'sites.change_status': ['sites.read', 'sites.update'],
  'sites.read_all': ['sites.read'],
  'masters.manage': ['masters.read'],
  'suppliers.manage': ['masters.read'],
  'customers.manage': ['masters.read'],
  'orders.create': ['orders.read', 'masters.read'],
  'orders.update': ['orders.read', 'masters.read'],
  'demand.import': ['orders.read', 'masters.read'],
  'inventory.read': ['masters.read'],
  'inventory.move': ['inventory.read'],
  'inventory.adjust': ['inventory.read'],
  'purchase.read': ['masters.read'],
  'purchase.create': ['purchase.read'],
  'purchase.approve': ['purchase.read'],
  'orders.read': ['masters.read'],
  'planning.read': ['masters.read'],
  'schedule.publish': ['planning.read'],
  'schedule.plan': ['planning.read'],
  'schedule.insert': ['planning.read'],
  'purchase.expedite': ['purchase.read', 'planning.read'],
  'production.execute': ['planning.read', 'orders.read'],
  'masters.cycle_time': ['planning.read', 'masters.read'],
  'planning.tools': ['planning.read'],
  'planning.run': ['planning.read'],
  'buffers.manage': ['planning.read'],
  // Each import type also requires its own maintain permission, checked by the API.
  'imports.create': ['masters.read'],
};
export const livePermissionCodes = [
  'dashboard.read',
  'users.read',
  'roles.read',
  'sites.read',
  'audit.read',
  'users.create',
  'users.update',
  'users.change_status',
  'users.assign_role',
  'users.invite',
  'users.reset_password',
  'users.retry_setup',
  'users.assign_plants',
  'roles.create',
  'roles.update',
  'roles.delete',
  'sites.create',
  'sites.update',
  'sites.change_status',
  'sites.read_all',
  'masters.read',
  'masters.manage',
  'suppliers.manage',
  'customers.manage',
  'imports.create',
  'orders.read',
  'orders.create',
  'orders.update',
  'demand.import',
  'inventory.read',
  'inventory.move',
  'inventory.adjust',
  'purchase.read',
  'purchase.create',
  'purchase.approve',
  'planning.read',
  'planning.run',
  'buffers.manage',
  'schedule.publish',
  'schedule.plan',
  'schedule.insert',
  'purchase.expedite',
  'production.execute',
  'masters.cycle_time',
  'planning.tools',
];

// Where a permission is actually felt: the module in the sidebar, and the screens it opens or
// unlocks. The roles screen groups by this, so granting a role is a question about menu entries
// ("who may insert an order?") rather than about permission codes.
export const permissionScreens = {
  'dashboard.read': ['Overview', 'Workspace overview'],
  'users.read': ['Users', 'Users'],
  'users.create': ['Users', 'Users'],
  'users.update': ['Users', 'Users'],
  'users.change_status': ['Users', 'Users'],
  'users.assign_role': ['Users', 'Users'],
  'users.invite': ['Users', 'Users'],
  'users.reset_password': ['Users', 'Users'],
  'users.retry_setup': ['Users', 'Users'],
  'users.assign_plants': ['Users', 'Users → plant access'],
  'roles.read': ['Roles & permissions', 'Roles & permissions'],
  'roles.create': ['Roles & permissions', 'Roles & permissions'],
  'roles.update': ['Roles & permissions', 'Roles & permissions'],
  'roles.delete': ['Roles & permissions', 'Roles & permissions'],
  'sites.read': ['Plants', 'Plants'],
  'sites.create': ['Plants', 'Plants'],
  'sites.update': ['Plants', 'Plants'],
  'sites.change_status': ['Plants', 'Plants'],
  'sites.read_all': ['Plants', 'Plants → every plant of the company'],
  'audit.read': ['Audit log', 'Audit log'],
  'masters.read': ['Availability', 'Every Availability screen'],
  'masters.manage': [
    'Availability',
    'Masters & setup: Units, Items, Calendars, Capacity & Changeover, Product Routing, BOMs, Stock locations',
  ],
  'suppliers.manage': ['Availability', 'Masters & setup: Suppliers, Item sourcing'],
  'customers.manage': ['Availability', 'Masters & setup: Customers'],
  'imports.create': ['Availability', 'Imports, File import'],
  'orders.read': ['Availability', 'Customer orders, Production orders, Demand History'],
  'orders.create': ['Availability', 'Customer orders, Production orders'],
  'orders.update': ['Availability', 'Customer orders'],
  'demand.import': ['Availability', 'Demand History'],
  'inventory.read': ['Availability', 'Stock, Stock & Service'],
  'inventory.move': ['Availability', 'Stock → receipts and issues'],
  'inventory.adjust': ['Availability', 'Stock → opening stock, adjustments, reversals'],
  'planning.read': ['Availability', 'Every planning screen of both engines'],
  'planning.run': ['Availability', 'Buffer Board & Exceptions → recalculate'],
  'buffers.manage': ['Availability', 'Parts & Buffer Profiles, Workbench'],
  'schedule.publish': ['Availability', 'Scheduler → publish the plan'],
  'schedule.plan': ['Availability', 'Scheduler, Club / date scenarios'],
  'schedule.insert': ['Availability', 'Insert an order, Pending Orders to Plan'],
  'production.execute': ['Availability', 'Execution Loop, Work Orders & Downtime'],
  'masters.cycle_time': ['Availability', 'Master-Data Audit → adopt a corrected cycle time'],
  'planning.tools': [
    'Availability',
    'Events & Seasons, Scheme Intake, Target Mode, Space Mode, Assumptions',
  ],
  'purchase.expedite': ['Availability', 'Material expedites'],
  'purchase.read': ['Availability', 'Proposed Orders, Buffers & POs'],
  'purchase.create': ['Availability', 'Buffers & POs'],
  'purchase.approve': ['Availability', 'Proposed Orders → approve or reject'],
  'work_orders.update': ['Production', 'Work Orders & Downtime'],
  'downtime.create': ['Production', 'Work Orders & Downtime'],
  'reports.export': ['Reporting', 'Exports'],
};

// The module and screens a permission belongs to, falling back to its catalogue module.
export function permissionPlacement(code, module = '') {
  const found = permissionScreens[code];
  return { module: found?.[0] ?? module, screens: found?.[1] ?? module };
}
