export const permissions = [
  ['dashboard.read', 'Dashboard', 'View workspace overview'],
  ['users.read', 'Users', 'View company users'],
  ['users.manage', 'Users', 'Manage company users'],
  ['roles.read', 'Roles', 'View roles and permissions'],
  ['roles.manage', 'Roles', 'Create, edit and delete custom roles'],
  ['sites.read', 'Plants', 'View assigned plants'],
  ['sites.manage', 'Plants', 'Create and edit plants; access all company plants'],
  ['audit.read', 'Audit log', 'Read company audit history'],
  ['masters.read', 'Masters', 'View planning master data'],
  ['masters.manage', 'Masters', 'Maintain planning masters'],
  ['imports.create', 'Masters', 'Validate and import files'],
  ['orders.read', 'Demand', 'View customer orders'],
  ['orders.create', 'Demand', 'Create customer orders'],
  ['inventory.read', 'Materials', 'View stock and movements'],
  ['inventory.adjust', 'Materials', 'Post authorised stock adjustments'],
  ['planning.read', 'Availability', 'View planning results'],
  ['planning.run', 'Availability', 'Run planning calculations'],
  ['schedule.publish', 'Availability', 'Publish a reviewed schedule'],
  ['purchase.read', 'Materials', 'View purchase proposals'],
  ['purchase.approve', 'Materials', 'Approve purchase proposals'],
  ['work_orders.update', 'Production', 'Record production progress'],
  ['downtime.create', 'Production', 'Record resource downtime'],
  ['reports.export', 'Reporting', 'Export authorised records'],
];
